name: API tests

on:
  workflow_dispatch:

jobs:

  api-tests:
    name: 'API tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Run API tests
        run: make test-api TEST_HOST=${{ vars.STAGING_HOST }}:${{ vars.STAGING_PORT }}

